### ISSUE TITLE
Merged Data Dataframe

### ISSUE THREAD

**Issue by michael-gvdw** [deepmAInd/empathic-art#21]

**Comment by michael-gvdw** [comment]
@A-shukla12 I suggest we use the following columns inorder to reffer and view the audio files:

- emotion
-  intesity
-  filename

If you have any extra suggestion let me know?!

**Comment by A-shukla12** [comment]
@michael-gvdw Those are great suggestions! We can also add the following column names: 

- Speaker 
- Duration 
- Sample Rate 
- Gender
- Statement

Let me know if these are alright.

**Comment by michael-gvdw** [comment]
Yeah just combine them all!

**Comment by michael-gvdw** [comment]
@A-shukla12  dont forget from what dataset they originate from something like a `dataname` column
